@GrowAcc_HostAddress = http://localhost:5144

### Registration for user
POST {{GrowAcc_HostAddress}}/User/registration/
Content-Type: application/json
Accept-Language: ua-UA


{
  "email" : "neyton61@gmail.com",
  "phoneNumber" : "+380671296329",
  "firstName" : "Mykyta",
  "lastName" : "Chystyi",
  "password" : "Pass1234!",
  "confirmPassword" : "Pass1234!"
}

### Confirm user account registration
GET {{GrowAcc_HostAddress}}/User/confirm?token=abcc69e8-223e-477b-862e-dd3a0d89b523
Accept: application/json
Accept-Language: ua-UA

### Send registration message again
GET {{GrowAcc_HostAddress}}/User/resendConfirmationEmail?email=neyton61@gmail.com
Accept: application/json
Accept-Language: ua-UA

### Login for user account
POST {{GrowAcc_HostAddress}}/user/login
Content-Type: application/json
Accept-Language: ua-UA


{
  "email" : "neyton61@gmail.com",
  "password" : "Pass1234!"
}

### Change password for user
POST {{GrowAcc_HostAddress}}/user/changePassword
Content-Type: application/json
Accept-Language: ua-UA

{
  "email" : "neyton61@gmail.com"
}

### 